services:
  migration:
    build: .
    command: npm run db:migrate
    environment:
      DATABASE_URL: file:/app/data/local.sqlite
    volumes:
      - ./data:/app/data
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      FACE_ENCODING_ENDPOINT: http://face-encoding:8000/v1/selfie
      DATABASE_URL: file:/app/data/local.sqlite
    volumes:
      - ./data:/app/data
    restart: always
    depends_on:
      - face-encoding
  face-encoding:
    ports:
      - "8000:8000"
    image: veriffdocker/face-encoding-test-task
    restart: always
